# Generated by Django 3.0.6 on 2021-04-14 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweet', '0002_tweet_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answerd_tweeted_date', models.DateField()),
                ('tweet_answer', models.CharField(max_length=280)),
                ('tweet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweet.Tweet')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
