# Generated by Django 3.0.6 on 2021-04-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tweeted_date', models.DateField()),
                ('tweet', models.CharField(max_length=280)),
                ('retweets', models.PositiveIntegerField(default=0)),
                ('favs', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
